### ISSUE TITLE
busybox-w32 as a lightweight shell?

### ISSUE THREAD

**Issue by ghost** [copperspice/cs_mingw_w64#10]
Originally proposed in #5. But the OP closed it.

You can download `busybox64.exe` and rename it `sh.exe`. You now have a working posix shell.

**Comment by ghost** [comment]
The w64devkit project has some patches over vanilla busybox-w32 to help the autotools build system to work correctly.

**Comment by bgeller** [comment]
Thank you for thinking about this, however you have missed a few things. The internals for this product have dependencies to a product we do not support.
