### ISSUE TITLE
Which version of cs_mingw_w64 to use with CopperSpice?

### ISSUE THREAD

**Issue by ghost** [copperspice/cs_mingw_w64#6]
I want to ask which version of cs_mingw_w64 is needed for [setup-CopperSpice-1.9.1-x64-MinGW.exe](https://download.copperspice.com/copperspice/binary/cs-1.9/setup-CopperSpice-1.9.1-x64-MinGW.exe). On your download server, there is only [mingw-cs-10.4-rc1.zip](https://download.copperspice.com/toolchain/mingw/mingw-cs-10.4-rc1.zip). It would be better if you bundle MinGW together with the CopperSpice installation package.

**Comment by bgeller** [comment]
> On your download server there is only . . . 

I guess you are referring to our web site where we have the current MinGW version our Windows CI is using. If you want to use version 11.4, 12.3, or 13.2 these binary files can be found in this github repo. 

CopperSpice can use any one of these MinGW versions.


>It would be better if you bundle MinGW together with the CopperSpice installation package.

Not every one uses MingGW on Windows so the size increase would be annoying for MSVC users. Also, no not everyone can use the same compiler version. The other problem is that MinGW and CS do not have releases at the same time so something would also be out of sync.

**Comment by ghost** [comment]
> Not every one uses MingGW on Windows so the size increase would be annoying for MSVC users. Also, no not everyone can use the same compiler version. The other problem is that MinGW and CS do not have releases at the same time so something would also be out of sync.

I'm talking about bundling MinGW with [setup-CopperSpice-1.9.1-x64-MinGW.exe](https://download.copperspice.com/copperspice/binary/cs-1.9/setup-CopperSpice-1.9.1-x64-MinGW.exe). MSVC users have their own installers.

**Comment by bgeller** [comment]
As we mentioned, the size of the bundle would be too large. The bigger question is which version should be included?  Some developers need to be on a specific version and other want to use the newest release. It is much better to keep MinGW and CS as separate downloads.
